# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'concat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(150, 40)
        Dialog.setMinimumSize(QtCore.QSize(150, 40))
        Dialog.setMaximumSize(QtCore.QSize(150, 40))
        Dialog.setStyleSheet("background-color : rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 10, 100, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(5, 5, 30, 30))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/resources/info.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "合并视频"))
        self.label.setText(_translate("Dialog", "正在合并视频...."))
import resources.resources
