# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/ui/ctvd_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(200, 210)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(25, 180, 150, 20))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 150, 20))
        self.label.setObjectName("label")
        self.lineEdit_file_save_path = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_file_save_path.setGeometry(QtCore.QRect(10, 30, 160, 20))
        self.lineEdit_file_save_path.setObjectName("lineEdit_file_save_path")
        self.pushButton_open = QtWidgets.QPushButton(Dialog)
        self.pushButton_open.setGeometry(QtCore.QRect(170, 30, 20, 20))
        self.pushButton_open.setObjectName("pushButton_open")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 55, 100, 20))
        self.label_2.setObjectName("label_2")
        self.spinBox_thread = QtWidgets.QSpinBox(Dialog)
        self.spinBox_thread.setGeometry(QtCore.QRect(130, 55, 60, 20))
        self.spinBox_thread.setProperty("value", 1)
        self.spinBox_thread.setObjectName("spinBox_thread")
        self.radioButton_ts = QtWidgets.QRadioButton(Dialog)
        self.radioButton_ts.setGeometry(QtCore.QRect(10, 155, 70, 20))
        self.radioButton_ts.setObjectName("radioButton_ts")
        self.radioButton_mp4 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_mp4.setGeometry(QtCore.QRect(120, 155, 70, 20))
        self.radioButton_mp4.setObjectName("radioButton_mp4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 150, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 105, 70, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 55, 20))
        self.label_5.setObjectName("label_5")
        self.spinBox_program_2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_program_2.setGeometry(QtCore.QRect(133, 80, 57, 20))
        self.spinBox_program_2.setMinimum(20)
        self.spinBox_program_2.setMaximum(999999)
        self.spinBox_program_2.setSingleStep(10)
        self.spinBox_program_2.setObjectName("spinBox_program_2")
        self.comboBox_quality = QtWidgets.QComboBox(Dialog)
        self.comboBox_quality.setGeometry(QtCore.QRect(80, 105, 110, 20))
        self.comboBox_quality.setObjectName("comboBox_quality")
        self.comboBox_quality.addItem("")
        self.comboBox_quality.addItem("")
        self.comboBox_quality.addItem("")
        self.comboBox_quality.addItem("")
        self.comboBox_quality.addItem("")
        self.spinBox_program_1 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_program_1.setGeometry(QtCore.QRect(65, 80, 57, 20))
        self.spinBox_program_1.setMinimum(0)
        self.spinBox_program_1.setMaximum(9999)
        self.spinBox_program_1.setSingleStep(10)
        self.spinBox_program_1.setObjectName("spinBox_program_1")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(124, 80, 10, 20))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "设置"))
        self.label.setText(_translate("Dialog", "文件保存位置:"))
        self.pushButton_open.setText(_translate("Dialog", "..."))
        self.label_2.setText(_translate("Dialog", "下载使用线程数:"))
        self.radioButton_ts.setText(_translate("Dialog", "不转码"))
        self.radioButton_mp4.setText(_translate("Dialog", "转码MP4"))
        self.label_3.setText(_translate("Dialog", "视频下载完成后是否转码?"))
        self.label_4.setText(_translate("Dialog", "视频清晰度:"))
        self.label_5.setText(_translate("Dialog", "节目区间:"))
        self.comboBox_quality.setItemText(0, _translate("Dialog", "最高画质(默认)"))
        self.comboBox_quality.setItemText(1, _translate("Dialog", "超清"))
        self.comboBox_quality.setItemText(2, _translate("Dialog", "高清"))
        self.comboBox_quality.setItemText(3, _translate("Dialog", "标清"))
        self.comboBox_quality.setItemText(4, _translate("Dialog", "流畅"))
        self.label_6.setText(_translate("Dialog", "-"))
